wandb_group_name: "largebatch_lrtune"

batch_size: 2048
num_iterations: 1800
warmdown_iters: 600

sweep:
  - optimizer_name: ["soap_muon10_full2"]
    precondition_frequency: 1
    learning_rate: [1.5e-2, 3.0e-2]
    lr_lm_head: [2.0e-3, 4.0e-3]
    lr_wte: [.25, .5]
    projection_type: "std"
    seed: [0, 1]
    nestrov: true
    newton_schulz_steps: 10
  - optimizer_name: ["soap_muon10_full2"]
    precondition_frequency: 1
    learning_rate: [3.0e-2, 6.0e-2]
    lr_lm_head: [4.0e-3, 8.0e-3]
    lr_wte: [.15, .3]
    projection_type: "std"
    seed: [0, 1]
    nestrov: true
    newton_schulz_steps: 10
