wandb_group_name: "soapsoap_wdfix_lr_sweep"

sweep:
  - optimizer_name: "soapsoap"
    precondition_frequency: [1, 10]
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .4
    projection_type: "std"
    seed: [0, 1, 2, 3]
  - optimizer_name: "soap"
    precondition_frequency: [1, 10]
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .4
    seed: [0, 1, 2, 3]
  - optimizer_name: "soapsoap"
    precondition_frequency: 1
    learning_rate: [1.5e-3, 3.0e-3]
    lr_lm_head: [1.0e-3, 2.0e-3]
    lr_wte: [.2, .4]
    projection_type: "std"
    seed: 2

