wandb_group_name: "soap_p_layer2"

sweep:
  - optimizer_name: ["soap_p_layer2"]
    precondition_frequency: 1
    learning_rate: [2.5e-4, 5.0e-4, 1.0e-3] 
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: -.25
    seed: 0
  - optimizer_name: ["soap_p_layer2"]
    precondition_frequency: 1
    learning_rate: [2.5e-4, 5.0e-4, 1.0e-3] 
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: -.5
    seed: 0
  - optimizer_name: ["soap_p_layer2"]
    precondition_frequency: 1
    learning_rate: 1.5e-4 
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: -.5
    seed: 0
