wandb_group_name: "soap_p"

sweep:
  - optimizer_name: "soap_p"
    precondition_frequency: 1
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: [0.5, 0.75, 0.9, 1.0]
    normalize_grads: [true, false]
    seed: 0
  - optimizer_name: "soap_p"
    precondition_frequency: 1
    learning_rate: [1.0e-3, 1.73e-3]
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: [0.5, 0.75, 0.9, 1.0]
    normalize_grads: [true, false]
    seed: 0
  - optimizer_name: "soap_p"
    precondition_frequency: 1
    learning_rate: [1.0e-3, 1.73e-3]
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: 1.1
    normalize_grads: [true, false]
    seed: 0
  - optimizer_name: "soap_p"
    precondition_frequency: 1
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: 1.1
    normalize_grads: [true, false]
    seed: 0
  - optimizer_name: "soap_p"
    precondition_frequency: 1
    learning_rate: [1.0e-3, 1.73e-3, 3.0e-3]
    lr_lm_head: 2.0e-3
    lr_wte: .4
    adam_power: [1.2, 1.3]
    normalize_grads: [true, false]
    seed: 0

