wandb_group_name: "sophia_largebatch"

sweep:
  - optimizer_name: "soap"
    precondition_frequency: 1
    learning_rate: [3.0e-3, 6.0e-3]
    lr_lm_head: [2.0e-3, 4.0e-3]
    lr_wte: [.3, .6]
    sophia_lambda: [1.0, .0001]
    batch_size: 2048
    num_iterations: 2000
    warmdown_iters: 650
  - optimizer_name: "muon"
    learning_rate: [2.0e-2, 4.0e-2]
    lr_lm_head: [2.0e-3, 4.0e-3]
    lr_wte: [.3, .6]
    batch_size: 2048
    num_iterations: 2000
    warmdown_iters: 650
  - optimizer_name: "soapsoap"
    precondition_frequency: 1
    learning_rate: [3.0e-3, 6.0e-3]
    lr_lm_head: [2.0e-3, 4.0e-3]
    lr_wte: [.3, .6]
    batch_size: 2048
    num_iterations: 2000
    warmdown_iters: 650
    projection_type: ["std", "right"]
  - optimizer_name: "soapsoap"
    precondition_frequency: 1
    learning_rate: [1.5e-3]
    lr_lm_head: [3.0e-3]
    lr_wte: [.3]
    batch_size: 2048
    num_iterations: 2000
    warmdown_iters: 650
    projection_type: ["std", "right"]

