wandb_group_name: "eps"

sweep:
  - optimizer_name: "soap"
    precondition_frequency: 10
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .3
    eps: [1e-8, 1e-12]
    seed: [0, 1, 2, 4]
