wandb_group_name: "test_it"

sweep:
  - optimizer_name: "soap_it"
    precondition_frequency: 10
    learning_rate: 3.0e-3
    lr_lm_head: 2.0e-3
    lr_wte: .4
    inner_loops: [3, 5]
    newton_schulz_steps: [3, 5]
    outer_loops: 1
    clip: false
    clip2: [true, false]
